# Numpy Basics
## import numpy as np


In [55]:
#importing numpy
import numpy as np

###### Tip !!
To see the documentation(i.e, the paramenters to pass) each functions press (shift + tab) after the brackets after the function name.

##### Numpy Arrays

In [56]:
#Creating a numpy array
my_list =[1,2,3,4]
arry = np.array(my_list)
arry

array([1, 2, 3, 4])

In [57]:
type(arry)
#type(my_list)

numpy.ndarray

In [58]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
print("list=",my_mat)#it prints the 2d list
a = np.array(my_mat)#it converts the list into a 2d array
a

list= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a[0,1] # Selecting element in row with index 0 and column with index 1

2

In [60]:
a[0,] # Selecting element in row with index 1 (and entire columns)

array([1, 2, 3])

###### Other ways of creating numpy arrays
(arange function,
zeros,
ones,
linspace)

In [61]:
#creating array by using 'arange' function it is same as range function bt arange  is use for array
np.arange(0,101,3)#it create array b/w 0 to 101 with step 3


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [62]:
# if u want to create array of zeros then
np.zeros(5)# single argument for 1d  zero array

array([0., 0., 0., 0., 0.])

In [63]:
#pass a tuple for dimension of array.it gives a row*column matrix on argument(n,m) 
# here a 2*5 matrix on argument of (2,5)
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
# if u want to create array of ones then
np.ones(5)# single argument for 1d  ones array

array([1., 1., 1., 1., 1.])

In [65]:
#pass tuple for dimmension of array. it give 5*5 matrix on argument of (5,5)
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
#linspace is use to create equally distributed point b/w any two numbers
np.linspace(0,5,10)#this create 10 equal points b/w 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [67]:
#creating identity matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
#array of random numbers b/w 0 to 1 uniformly distributed
np.random.rand(5)#it return 5 random number

array([0.4967636 , 0.34648703, 0.15717074, 0.18750092, 0.75462157])

In [69]:
np.random.rand(5,3)#it return 2d matrix of random number bt 0 to 1

array([[0.94474352, 0.31858623, 0.76863452],
       [0.52846121, 0.61821756, 0.38404163],
       [0.33726271, 0.77449295, 0.69223252],
       [0.40032259, 0.98172318, 0.59607121],
       [0.69152133, 0.83125977, 0.87499317]])

In [70]:
#if u want random number from normal distribution or gaussian distribution then use np.rnadom.randn()
np.random.randn(3,5)#it return 3*5 matrix of non uniform random number from normal distribution

array([[ 0.50199991,  1.11060951, -1.42876675,  0.24227453, -1.36873489],
       [-0.34947901,  0.9846373 , -2.37640291,  1.61029369, -0.23455523],
       [ 0.06439027, -1.35376245, -0.36488563,  0.52465135, -1.63832406]])

In [71]:
#if u want random integer number b/w any two number
np.random.randint(1,100)#it return a int random number b/w 1 to 100

61

In [72]:
np.random.randint(1,100,10)#it return 10 int random number b/w 1 to 100

array([87, 18,  6, 20, 36, 89, 69, 18, 79, 79])

In [73]:
#reshaping the array
ar=np.arange(0,25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
ar_1=ar.reshape(5,5)#it will convrt 1d array into 2d of 5*5 matrix
ar_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
#to know dimension of array
ar_1.shape

(5, 5)

In [76]:
# to know data typ of array
ar_1.dtype

dtype('int32')

### Indexing in array

In [77]:
#value in the array can be access same as list by indexing and slicing
ary=np.arange(0,25) 
ary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
ary[3:22]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21])

In [79]:
ary[23]

23

In [80]:
#changing value of array
ary[0:10]=50
ary

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [81]:
ary[:]=100
ary

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [82]:
ary= np.arange(0,11)
ary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
#comparison of arrays
ary>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [84]:
bool_ary= ary>5
bool_ary

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [85]:
ary[ary>5]#if we write in this way it only returns true value 

array([ 6,  7,  8,  9, 10])

In [86]:
#create 2d array in one line
arrry= np.arange(0,25).reshape(5,5)
arrry

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Numpy operations
#### array with array
#### array with scalars
#### universal array function

In [87]:
#array with array
arrry

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
arrry + arrry#array addition

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [89]:
arrry - arrry#array substraction

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [90]:
arrry / arrry#array division
#0/0 will not give error it only give warning

C:\Users\Siddesh Naik\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [91]:
arrry * arrry#array multiplication

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [92]:
#array with scaler
arrry + 100

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124]])

In [93]:
arrry * 100

array([[   0,  100,  200,  300,  400],
       [ 500,  600,  700,  800,  900],
       [1000, 1100, 1200, 1300, 1400],
       [1500, 1600, 1700, 1800, 1900],
       [2000, 2100, 2200, 2300, 2400]])

In [94]:
arrry -100

array([[-100,  -99,  -98,  -97,  -96],
       [ -95,  -94,  -93,  -92,  -91],
       [ -90,  -89,  -88,  -87,  -86],
       [ -85,  -84,  -83,  -82,  -81],
       [ -80,  -79,  -78,  -77,  -76]])

In [95]:
arrry / 10

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4]])

In [96]:
arrry ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

In [97]:
#universal Array function
np.sqrt(arrry)    

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

In [98]:
np.exp(arrry)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10]])

In [99]:
np.max(arrry)   #or max(arrry)can also be used without np.

24

In [100]:
np.min(arrry)

0

In [101]:
np.sin(arrry)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

In [102]:
np.log(arrry)

C:\Users\Siddesh Naik\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383]])

In [103]:
np.cos(arrry)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722],
       [-0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901]])

In [104]:
np.tan(arrry)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01,  1.15782128e+00],
       [-3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
        -6.79971146e+00, -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
         4.63021133e-01,  7.24460662e+00],
       [-8.55993401e-01,  3.00632242e-01,  3.49391565e+00,
        -1.13731371e+00,  1.51589471e-01],
       [ 2.23716094e+00, -1.52749853e+00,  8.85165604e-03,
         1.58815308e+00, -2.13489670e+00]])

In [105]:
np.tanh(arrry)

array([[0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ],
       [0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])

In [106]:
np.cosh(arrry)

array([[1.00000000e+00, 1.54308063e+00, 3.76219569e+00, 1.00676620e+01,
        2.73082328e+01],
       [7.42099485e+01, 2.01715636e+02, 5.48317035e+02, 1.49047916e+03,
        4.05154203e+03],
       [1.10132329e+04, 2.99370709e+04, 8.13773957e+04, 2.21206696e+05,
        6.01302142e+05],
       [1.63450869e+06, 4.44305526e+06, 1.20774764e+07, 3.28299846e+07,
        8.92411505e+07],
       [2.42582598e+08, 6.59407867e+08, 1.79245642e+09, 4.87240172e+09,
        1.32445611e+10]])

In [107]:
np.sinh(arrry)

array([[0.00000000e+00, 1.17520119e+00, 3.62686041e+00, 1.00178749e+01,
        2.72899172e+01],
       [7.42032106e+01, 2.01713157e+02, 5.48316123e+02, 1.49047883e+03,
        4.05154190e+03],
       [1.10132329e+04, 2.99370708e+04, 8.13773957e+04, 2.21206696e+05,
        6.01302142e+05],
       [1.63450869e+06, 4.44305526e+06, 1.20774764e+07, 3.28299846e+07,
        8.92411505e+07],
       [2.42582598e+08, 6.59407867e+08, 1.79245642e+09, 4.87240172e+09,
        1.32445611e+10]])